name: Generate executables and post them to release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-executables:
    name: Generation of Linux executable
    runs-on: ubuntu-latest.version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'

      - name: Install dependencies
        id: install_dependencies
        run: |
          cargo install cargo-get && cargo clean
          echo "::set-output name=APP_VERSION::$(cargo get version)"

      - name: Get release
        id: get_release
        uses: leahlundqvist/get-release@v1.3.1
        with:
          tag_name: ${{ steps.install_dependencies.outputs.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build Linux x86_64
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl

      - name: Upload Linux x86_64 executable to releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-musl/release/asthobin
          asset_name: asthobin-${{ steps.install_dependencies.outputs.APP_VERSION }}-x86_64-linux
          asset_content_type: application/octet-stream